apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: database-source-kustomization
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./Database
  prune: true
  sourceRef:
    kind: GitRepository
    name: source-manifests
    namespace: flux-system
  targetNamespace: three-tier 